- name: Create a VM in VMware
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a VM from a template
      community.vmware.vmware_guest:
        validate_certs: false
        cluster: "{{ vm_cluster }}"
        datacenter: "{{ vm_dc }}"
        folder: "{{ vm_folder }}" 
        datastore: "{{ vm_datastore }}"
        name: "{{ vm_name }}"
        template: "{{ vm_source_template}}"
      register: new_vm
      
    - name: Show results of creation
      ansible.builtin.debug:
        var: new_vm
        
    - name: Second step, use the same name to customize said VM
      community.vmware.vmware_guest:
        validate_certs: false
        cluster: "{{ vm_cluster }}"
        datacenter: "{{ vm_dc }}"
        folder: "{{ vm_folder }}" 
        datastore: "{{ vm_datastore }}"
        name: "{{ vm_name }}"
        networks:
          - name: "{{ vm_network }}"
      tags:
        - networkconfig

